service: twitter-trends
org: yeachan153

frameworkVersion: '2'

provider:
  name: aws
  layers:
    # - arn:aws:lambda:eu-central-1:534692912862:layer:analyzer_layer:1
    - arn:aws:lambda:eu-central-1:534692912862:layer:analyzer_layer:2
  runtime: python3.7
  region: eu-central-1
  deploymentBucket: fedex-case-serverless-deploy
  memorySize: 512
  environment:
    region: "eu-central-1"
    bucket_name: "fedex-case"
    filter_location: "amsterdam"
    dynamo_table: twitter_analysis_fedex
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::fedex-case
        - arn:aws:s3:::fedex-case/*
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"

functions:
  analyser:
    handler: analyser.analyse
    timeout: 900
    reservedConcurrency: 1

  query:
    handler: query.handler
    timeout: 30
    reservedConcurrency: 20
    events:
      - http: GET query
